### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by xuguan** [xuguan/myNetworkTools#1]
记事本编辑updateHosts.bat，再用github desktop 上传，出现了乱码

**Comment by smallOnion** [comment]
可以可以

**Comment by xuguan** [comment]
记事本编辑，保存时选择utf-8编码，而不是默认的ANSI编码。

一开始找到[GitHub 第一坑：换行符自动转换](https://github.com/cssmagic/blog/issues/22) 这篇issue，我以为是个很大的问题。
